# Generated by Django 3.2.3 on 2021-05-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gallerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallerie', to='service.gallerie'),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='service.categorie'),
        ),
    ]
