# Generated by Django 3.2.3 on 2021-05-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210518_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelouse_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonsaison', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='image_service')),
                ('description', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prestations',
            name='icone',
            field=models.CharField(max_length=200),
        ),
    ]
