# Generated by Django 3.2.3 on 2021-05-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_alter_about_option_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_about',
            name='image',
        ),
    ]
