# Generated by Django 3.2.3 on 2021-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_remove_option_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_about',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
