# Generated by Django 3.2.3 on 2021-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_alter_option_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='lien',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
