# Generated by Django 3.2.3 on 2021-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_auto_20210518_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignages',
            name='nom',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
